repos:
- repo: local
  hooks:
  - id: nixpkgs-fmt
    name: nixpkgs-fmt
    description: Format nix code with nixpkgs-fmt.
    entry: nixpkgs-fmt
    language: system
    files: \.nix$
    minimum_pre_commit_version: 1.18.1
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
  - id: shellcheck
